"""Synthetic dataset for the building_materials vertical (PLAN-0016 scaffold).

Generated by ``vero-lite new-vertical`` — a minimal, deterministic starting
point (no external I/O, reproducible). Shapes match the vertical ontology.

⚠ DRAFT FOR HUMAN REVIEW (ADR-0015 D5): review + enrich these records (domain-
plausible names, a fuller timeline) before the demo. The breach event is the
timeline's final beat so real-time anchoring (PLAN-0015 D1) leaves nothing in the
future.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


def branch_records() -> list[dict[str, Any]]:
    """Return the synthetic Branch records (geo-bearing)."""
    return [
        {
            "branch_id": "branch-01",
            "name": "สาขาบางนา (คลังวัสดุก่อสร้าง)",
            "branch_type": "flagship",
            "lat": 13.6687,
            "lng": 100.6051,
        },
    ]


def customeraccount_records() -> list[dict[str, Any]]:
    """Return the synthetic CustomerAccount records."""
    return [
        {
            "account_id": "customeraccount-01",
            "name": "หจก. ศรีสมบูรณ์ก่อสร้าง",
            "customer_type": "contractor",
            "credit_limit_thb": 500000.0,
            "payment_terms_days": 45.0,
            "risk_grade": "b",
            "status": "active",
            "site_id": "branch-01",
        },
    ]


def operational_events() -> list[dict[str, Any]]:
    """Return the synthetic OperationalEvent records (baseline + breach)."""
    return [
        {
            "event_id": "event-reading-01",
            "event_type": "reading",
            "severity": "info",
            "measured_value": 250000.0,
            "unit": "THB",
            "description": "ยอดค้างเครดิต 250,000 บาท — ต่ำกว่าวงเงิน 500,000 บาท (ปกติ).",
            "occurred_at": datetime(2026, 6, 1, 1, 30, tzinfo=UTC),
            "account_id": "customeraccount-01",
            "site_id": "branch-01",
        },
        {
            "event_id": "event-reading-02",
            "event_type": "reading",
            "severity": "critical",
            "measured_value": 550000.0,
            "unit": "THB",
            "description": "ยอดค้างเครดิตพุ่งเป็น 550,000 บาท — เกินวงเงิน 500,000 บาท จากออเดอร์ด่วน.",
            "occurred_at": datetime(2026, 6, 1, 2, 0, tzinfo=UTC),
            "account_id": "customeraccount-01",
            "site_id": "branch-01",
        },
    ]


OBJECT_SOURCES = {
    "Branch": branch_records,
    "CustomerAccount": customeraccount_records,
}
