"""The oracle for PLAN-0121: what the battery reports when its own child is cut off.

🔴 **Why this module is separate from `test_probe_battery.py`, and why it must be.**
PLAN-0121 changes `_outcome.py` and `_battery.py` — *the instrument that witnesses this
PLAN's own probes*. §2.3: a defect that makes the judge **under**-fire (fail to downgrade
an aborted child) is invisible to the battery, because the battery's own children over
these tests exit 0 or 1, never 75. So the oracle for that half is out-of-band: direct unit
tests over `classify` / `parse_junit` / `_make_pytest_runner`, fed the aborted shapes. The
oracle judges the instrument; the battery only witnesses that the oracle is *live*.

🔴 **Nothing here is simulated**, per the doctrine of `test_probe_battery.py`. Every junit
report is produced by a real pytest run over a real scratch project, and the three abort
shapes are generated by this module rather than transcribed — a hand-written `<testcase>`
would be checking this author's model of pytest instead of pytest, which is the exact
defect the package exists to stop.

The committed `fixtures/probe_battery/` captures are the *other* half: a closed incident
from session 277, pinned so a pytest upgrade that changes the shape is loud rather than
silent. The live shapes pin the present, the fixtures pin the incident, and
`test_the_live_body_shape_matches_the_s277_signature` is what says when they part.

Every test carries exactly ONE claim, so a mutation can only ever hide behind one
assertion at a time.
"""

from __future__ import annotations

import json
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from tools.probe_battery import (
    VERDICT_EXIT_CODES,
    Battery,
    Outcome,
    Probe,
    RunRecord,
    classify,
    parse_junit,
    run_battery,
)
from tools.probe_battery._battery import (
    _classify_probe,
    _DeferredInterrupts,
    _make_pytest_runner,
)
from tools.probe_battery._outcome import (
    ABORT_LEAD_EXIT_CODE,
    ABORT_LEAD_SHAPE,
    UNNAMED_CASE,
)
from tools.probe_battery._snapshot import RunStore
from tools.probe_coverage import Claim, enumerate_claims

FIXTURES = Path(__file__).parent / "fixtures" / "probe_battery"

#: Mimics the *shape* of the token PLAN-0120's guard will print, without importing
#: anything from it — `tests/db_guard.py` does not exist (PLAN-0121 B20) and this PLAN must
#: stay executable before, after, or without PLAN-0120.
REASON = "TEST-DB-GUARD outcome=CONTENDED holder_pid=424242 db=vero_lite_test_s279"

#: Bounds every spawned pytest, so a regression reddens rather than hangs the suite.
SPAWN_TIMEOUT_S = 120

# ======================================================================================
# The three live shapes — each from one real pytest run
# ======================================================================================

_BODY_MODULE = f"""import pytest


def test_green():
    assert "green-marker" == "green-marker"


def test_aborts_in_the_body():
    pytest.exit({REASON!r}, returncode=75)
    assert "unreachable" == "unreachable"
"""

_PLAIN_MODULE = """def test_green():
    assert "green-marker" == "green-marker"
"""

#: Collects nothing at all — the shape that really does yield rc=5. Measured (s279): a
#: nonexistent NODE ID gives rc=4, not rc=5, which is why this is a module without tests
#: rather than a bad selector.
_NO_TESTS_MODULE = """def helper_not_a_test():
    return "nothing here is collected"
"""

_ABORTING_CONFTEST = f"""import pytest


@pytest.fixture(autouse=True)
def _guard_acquire():
    pytest.exit({REASON!r}, returncode=75)
"""

#: A conftest that raises at IMPORT: pytest writes the cause to **stderr** and produces no
#: junit file at all. It is the shape that proves the runner's stderr merge is load-bearing.
_UNIMPORTABLE_CONFTEST = "import definitely_not_a_real_module_s279  # noqa: F401\n"


def _spawn(project: Path, node: str | None = None) -> RunRecord:
    """Run the battery's argv verbatim over `project` and keep everything it left behind.

    Deliberately mirrors `_battery._run` rather than calling it: these tests are the oracle
    for that function's *contract*, and the ones that must exercise the real runner do so
    explicitly (`test_the_runner_returns_the_childs_exit_code`,
    `test_a_child_that_produces_no_report_names_its_cause`).
    """
    xml = project / "junit.xml"
    argv = [sys.executable, "-m", "pytest"]
    if node is not None:
        argv.append(node)
    argv += [f"--junitxml={xml}", "-p", "no:cacheprovider", "-q"]
    proc = subprocess.run(
        argv,
        cwd=str(project),
        capture_output=True,
        text=True,
        check=False,
        timeout=SPAWN_TIMEOUT_S,
    )
    return RunRecord(
        xml_text=xml.read_text(encoding="utf-8") if xml.exists() else None,
        returncode=proc.returncode,
        stdout_tail=proc.stdout + proc.stderr,
    )


def _project(tmp: Path, name: str, files: dict[str, str]) -> Path:
    p = tmp / name
    p.mkdir(parents=True, exist_ok=True)
    for filename, body in files.items():
        (p / filename).write_text(body, encoding="utf-8")
    return p


@pytest.fixture(scope="module")
def body_shape(tmp_path_factory: pytest.TempPathFactory) -> RunRecord:
    """Shape (i): a green test, then `pytest.exit(..., returncode=75)` from a test BODY.

    The green runs FIRST on purpose. Measured: the report then carries **both** a named
    passed `<testcase>` and the nameless one the abort leaves, from a single run — which is
    what lets the positive control below come from the same pytest invocation as the
    subject rather than from a second, differently-configured one.
    """
    project = _project(tmp_path_factory.mktemp("body"), "proj", {"test_shapes.py": _BODY_MODULE})
    return _spawn(project)


@pytest.fixture(scope="module")
def fixture_shape(tmp_path_factory: pytest.TempPathFactory) -> RunRecord:
    """Shape (ii): an autouse fixture aborts, so the report holds no `<testcase>` at all."""
    project = _project(
        tmp_path_factory.mktemp("fix"),
        "proj",
        {"conftest.py": _ABORTING_CONFTEST, "test_shapes.py": _PLAIN_MODULE},
    )
    return _spawn(project)


@pytest.fixture(scope="module")
def unimportable_project(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Shape (iii): the conftest raises at import — no junit file, cause on stderr."""
    return _project(
        tmp_path_factory.mktemp("bad"),
        "proj",
        {"conftest.py": _UNIMPORTABLE_CONFTEST, "test_shapes.py": _PLAIN_MODULE},
    )


@pytest.fixture(scope="module")
def declared(tmp_path_factory: pytest.TempPathFactory) -> tuple[Claim, Path]:
    """A real enumerated claim, via the real enumerator — never a hand-built key."""
    path = tmp_path_factory.mktemp("claim") / "test_shapes.py"
    path.write_text(_BODY_MODULE, encoding="utf-8")
    matches = [c for c in enumerate_claims(path) if "green-marker" in c.source]
    assert len(matches) == 1, f"expected 1 claim, got {len(matches)}"
    return matches[0], path


def _classify(record: RunRecord, declared: tuple[Claim, Path], *, with_rc: bool = True):
    claim, path = declared
    assert record.xml_text is not None
    return classify(
        parse_junit(record.xml_text),
        claim,
        path,
        path.parent,
        returncode=record.returncode if with_rc else None,
        stdout_tail=record.stdout_tail if with_rc else "",
    )


def _subset(xml_text: str, name: str) -> str:
    """Re-scope a report to the one `<testcase>` a node id would select — moved, not built."""
    root = ET.fromstring(xml_text)  # noqa: S314 - our own pytest's output
    suites = ET.Element("testsuites")
    suite = ET.SubElement(suites, "testsuite", {"name": "subset"})
    suite.extend([c for c in root.iter("testcase") if c.get("name") == name])
    return ET.tostring(suites, encoding="unicode")


# ======================================================================================
# AC-1 — a body-phase abort is ABORTED, not GREEN
# ======================================================================================


def test_an_exit_from_the_test_body_is_aborted_not_green(
    body_shape: RunRecord, declared: tuple[Claim, Path], capsys: pytest.CaptureFixture[str]
) -> None:
    """🔴 The defect this PLAN exists to remove, at its own site.

    The pass read is a CONJUNCTION, and deliberately so (PLAN-0121 AC-1 as amended in
    s279): both defence layers fire on this shape, so `is ABORTED` alone cannot redden when
    the exit-code layer is disabled — layer 2 catches the same report and returns the same
    outcome. The lead clause is the only observable that separates them.
    """
    result = _classify(body_shape, declared)
    cases = parse_junit(body_shape.xml_text or "")
    unnamed = sum(1 for c in cases if c.name == UNNAMED_CASE)
    print(
        f"rc={body_shape.returncode} cases={len(cases)} unnamed={unnamed} "
        f"outcome={result.outcome} lead="
        f"{'exit_code' if result.reason.startswith(ABORT_LEAD_EXIT_CODE) else 'shape'}"
    )
    capsys.readouterr()
    assert result.outcome is Outcome.ABORTED and result.reason.startswith(ABORT_LEAD_EXIT_CODE)


def test_a_real_green_is_still_green(body_shape: RunRecord, declared: tuple[Claim, Path]) -> None:
    """The positive control, from the SAME pytest run as the subject above."""
    claim, path = declared
    cases = parse_junit(_subset(body_shape.xml_text or "", "test_green"))
    result = classify(cases, claim, path, path.parent, returncode=0, stdout_tail="")
    unnamed = sum(1 for c in cases if c.name == UNNAMED_CASE)
    print(f"rc=0 cases={len(cases)} unnamed={unnamed} outcome={result.outcome}")
    assert result.outcome is Outcome.GREEN


# ======================================================================================
# AC-2 — a fixture-phase abort is ABORTED, not NO-TESTS; the code set is pytest's own
# ======================================================================================


def test_an_exit_from_a_fixture_is_aborted_not_no_tests(
    fixture_shape: RunRecord, declared: tuple[Claim, Path]
) -> None:
    """The discriminating case: an EMPTY report, which only the exit code can read.

    No `<testcase>` exists, so the shape layer has nothing to look at. Before PLAN-0121
    this reported "the node id selected no tests", pointing a reader at their own argv.
    """
    result = _classify(fixture_shape, declared)
    cases = parse_junit(fixture_shape.xml_text or "")
    print(f"rc={fixture_shape.returncode} cases={len(cases)} outcome={result.outcome}")
    assert result.outcome is Outcome.ABORTED


def test_a_run_that_collected_nothing_is_still_no_tests(
    tmp_path: Path, declared: tuple[Claim, Path]
) -> None:
    """Positive control for AC-2: a genuinely empty collection must still read NO-TESTS.

    `rc=5` (NO_TESTS_COLLECTED) is a verdict code — pytest ran to completion and its
    account of what ran is complete — so the abort arm must NOT fire on it. Without this
    control, AC-2's subject would be satisfied by a classifier that answered ABORTED to
    every empty report.

    🔴 The shape is a module with **no test functions**, not a nonexistent node id. PLAN-0121
    AC-2 specified the latter and predicted `rc=5`; measured on the pinned pytest (9.0.3) a
    nonexistent node id gives **rc=4** (USAGE_ERROR, `no match in any of [...]`) and
    therefore — correctly — reads ABORTED. Amended in s279 with the measurement; see
    `test_a_nonexistent_node_id_is_aborted_not_no_tests` for the case that displaced it.
    """
    project = _project(tmp_path, "proj", {"test_empty.py": _NO_TESTS_MODULE})
    record = _spawn(project)
    result = _classify(record, declared)
    print(f"rc={record.returncode} outcome={result.outcome}")
    assert result.outcome is Outcome.NO_TESTS


def test_a_nonexistent_node_id_is_aborted_not_no_tests(
    tmp_path: Path, declared: tuple[Claim, Path]
) -> None:
    """The case that displaced AC-2's original control, kept because it is a real reading.

    A node id that matches nothing is a **usage error** (rc=4), not a complete account of a
    run — so it downgrades, and the reason carries pytest's own explanation rather than the
    driver's guess. Measured, not assumed: this is what made the original control red.
    """
    project = _project(tmp_path, "proj", {"test_shapes.py": _PLAIN_MODULE})
    record = _spawn(project, node="test_shapes.py::test_does_not_exist_s279")
    result = _classify(record, declared)
    print(f"rc={record.returncode} outcome={result.outcome} reason={result.reason!r}")
    assert result.outcome is Outcome.ABORTED and "no match in any of" in result.reason


def test_the_verdict_exit_codes_are_pytests_own() -> None:
    """The cross-file pin. `tools/` keeps integer literals and takes no pytest dependency;
    this test imports `pytest.ExitCode` so a pytest that renumbered them would redden here
    rather than silently widen what the driver treats as a complete report."""
    expected = {
        int(pytest.ExitCode.OK),
        int(pytest.ExitCode.TESTS_FAILED),
        int(pytest.ExitCode.NO_TESTS_COLLECTED),
    }
    print(f"VERDICT_EXIT_CODES={sorted(VERDICT_EXIT_CODES)} pytest={sorted(expected)}")
    assert set(VERDICT_EXIT_CODES) == expected


# ======================================================================================
# AC-3 — the reason names the cause, in both no-verdict shapes
# ======================================================================================


def test_the_aborted_reason_carries_the_childs_last_line(
    body_shape: RunRecord, declared: tuple[Claim, Path]
) -> None:
    """The cause exists in exactly one place — the child's stdout — and nowhere in the XML.

    A reason that lost it would name an infrastructure event without naming the event.
    """
    result = _classify(body_shape, declared)
    print(f"reason={result.reason!r}")
    assert "outcome=CONTENDED holder_pid=424242" in result.reason


def test_the_aborted_reason_carries_the_exit_code(
    body_shape: RunRecord, declared: tuple[Claim, Path]
) -> None:
    """Sibling claim of the one above, split out: one assertion per test."""
    result = _classify(body_shape, declared)
    print(f"rc={body_shape.returncode} reason={result.reason!r}")
    assert "rc=75" in result.reason


_RED_MODULE = """def test_ordinary_red():
    assert "red-marker" == "red-MARKER"
"""


def test_an_ordinary_reds_message_is_still_carried(tmp_path: Path) -> None:
    """🟢 POSITIVE CONTROL for AC-3, and for §2.2's asymmetry as a whole.

    Everything else in this module is about the abort path. This one says the ordinary
    path still works: a real assertion failing at its own site is still WITNESSED, and its
    message still reaches the reason. If PLAN-0121 had broken the legible-RED reading, no
    other test here would say so.

    🔴 It lives in THIS module rather than being cited from `test_probe_battery.py`,
    because `check_ac_consistency` Check 3 is right to refuse a ticked AC whose evidence
    sits in a module no battery's `claim_sources` covers — the coverage report would have
    been computed over a denominator that excluded it (found s279, by the guard).
    """
    project = _project(tmp_path, "proj", {"test_shapes.py": _RED_MODULE})
    record = _spawn(project)
    claim = next(
        c for c in enumerate_claims(project / "test_shapes.py") if "red-marker" in c.source
    )
    assert record.xml_text is not None
    result = classify(
        parse_junit(record.xml_text),
        claim,
        project / "test_shapes.py",
        project,
        returncode=record.returncode,
        stdout_tail=record.stdout_tail,
    )
    print(f"rc={record.returncode} outcome={result.outcome} reason={result.reason!r}")
    assert result.outcome is Outcome.WITNESSED and "red-MARKER" in result.reason


def test_a_child_that_produces_no_report_names_its_cause(
    unimportable_project: Path, tmp_path: Path
) -> None:
    """Through the REAL runner: a conftest that will not import writes to **stderr** only.

    Without the runner's `stderr=subprocess.STDOUT` merge the cause line is not in the tail
    at all, and the reason falls back to "it failed to start, or it was killed at the
    timeout" — the guess PLAN-0121 removes. The measured rc is printed rather than
    asserted: B30's `4` was drafter knowledge, and the read here is "a non-verdict code and
    the cause text is present".
    """
    store = RunStore.begin(unimportable_project, tmp_path / "state")
    runner = _make_pytest_runner(store, _DeferredInterrupts())
    probe = Probe(
        name="P",
        subject=Path("conftest.py"),
        old="x",
        new="y",
        node_id="test_shapes.py::test_green",
        expect_claim="unused",
    )
    record = runner(probe, unimportable_project, SPAWN_TIMEOUT_S)
    assert record is not None
    classification = _classify_probe(probe, {}, unimportable_project, record, SPAWN_TIMEOUT_S)
    print(
        f"rc={record.returncode} xml_is_none={record.xml_text is None} "
        f"reason={classification.reason!r}"
    )
    assert "definitely_not_a_real_module_s279" in classification.reason


def test_a_child_that_produces_no_report_returns_a_record_not_none(
    unimportable_project: Path, tmp_path: Path
) -> None:
    """Sibling claim: the record must EXIST with `xml_text is None`.

    A bare `None` is reserved for the timeout path. Collapsing the two is what made the old
    message have to guess between "failed to start" and "killed at the timeout".
    """
    store = RunStore.begin(unimportable_project, tmp_path / "state")
    runner = _make_pytest_runner(store, _DeferredInterrupts())
    probe = Probe(
        name="P",
        subject=Path("conftest.py"),
        old="x",
        new="y",
        node_id="test_shapes.py::test_green",
        expect_claim="unused",
    )
    record = runner(probe, unimportable_project, SPAWN_TIMEOUT_S)
    print(f"record_is_none={record is None} rc={record.returncode if record else '-'}")
    assert record is not None and record.xml_text is None


# ======================================================================================
# AC-4 — the real driver, end to end
# ======================================================================================


def test_the_runner_returns_the_childs_exit_code(tmp_path: Path) -> None:
    """The value `_run` used to discard. Everything downstream of it depends on this one."""
    project = _project(tmp_path, "proj", {"test_shapes.py": _BODY_MODULE})
    store = RunStore.begin(project, tmp_path / "state")
    runner = _make_pytest_runner(store, _DeferredInterrupts())
    probe = Probe(
        name="P",
        subject=Path("test_shapes.py"),
        old="x",
        new="y",
        node_id="test_shapes.py::test_aborts_in_the_body",
        expect_claim="unused",
    )
    record = runner(probe, project, SPAWN_TIMEOUT_S)
    assert record is not None
    print(f"returncode={record.returncode} tail_bytes={len(record.stdout_tail)}")
    assert record.returncode == 75


def test_the_runner_keeps_the_childs_last_line(tmp_path: Path) -> None:
    """Sibling claim: the merged output survives the subprocess boundary."""
    project = _project(tmp_path, "proj", {"test_shapes.py": _BODY_MODULE})
    store = RunStore.begin(project, tmp_path / "state")
    runner = _make_pytest_runner(store, _DeferredInterrupts())
    probe = Probe(
        name="P",
        subject=Path("test_shapes.py"),
        old="x",
        new="y",
        node_id="test_shapes.py::test_aborts_in_the_body",
        expect_claim="unused",
    )
    record = runner(probe, project, SPAWN_TIMEOUT_S)
    assert record is not None
    # 🔴 The empty case is the one this test exists to catch, so the diagnostic must
    # survive it. Probe P11 (which empties the tail) first reported CRASHED here, on an
    # IndexError from `splitlines()[-1]` — the print raised before the assertion below
    # could run, hiding the very reading it was added to expose.
    lines = record.stdout_tail.strip().splitlines()
    print(f"tail_bytes={len(record.stdout_tail)} " f"last={lines[-1] if lines else '<empty>'!r}")
    assert "outcome=CONTENDED holder_pid=424242" in record.stdout_tail


_SUBJECT = """def classify(n):
    if n > 10:
        return "high"
    return "low"
"""

_ABORTING_PROBE_TEST = f"""import pytest


def test_slow_claim():
    pytest.exit({REASON!r}, returncode=75)
    assert classify(20) == "high"
"""


def _aborting_battery(tmp_path: Path) -> tuple[Battery, Path]:
    project = _project(
        tmp_path,
        "proj",
        {"subject.py": _SUBJECT, "test_slow.py": _ABORTING_PROBE_TEST},
    )
    (project / "state").mkdir(exist_ok=True)
    probe = Probe(
        name="P1",
        subject=Path("subject.py"),
        old="n > 10",
        new="n > 1000",
        node_id="test_slow.py::test_slow_claim",
        expect_claim='test_slow_claim|classify(20) == "high"|#0',
    )
    return Battery(claim_sources=(project / "test_slow.py",), probes=(probe,)), project


def test_an_aborted_probe_credits_nothing(tmp_path: Path) -> None:
    """🔴 The safety half, through the whole driver rather than the classifier alone.

    A cut-off child proves nothing about the guard, so it must never credit. This was
    already true before PLAN-0121 (`CREDITING_OUTCOMES` holds only WITNESSED) and the test
    is here to keep it true — §2.2's asymmetry argument rests on it.
    """
    battery, project = _aborting_battery(tmp_path)
    result = run_battery(
        battery,
        project_root=project,
        state_base=project / "state",
        timeout_s=SPAWN_TIMEOUT_S,
        echo=False,
    )
    print(f"credited={len(result.credited)} outcome={result.results[0].classification.outcome}")
    assert result.credited == {}


def test_an_aborted_probe_is_reported_aborted(tmp_path: Path) -> None:
    """Sibling claim: the outcome the report shows a reader."""
    battery, project = _aborting_battery(tmp_path)
    result = run_battery(
        battery,
        project_root=project,
        state_base=project / "state",
        timeout_s=SPAWN_TIMEOUT_S,
        echo=False,
    )
    classification = result.results[0].classification
    print(f"outcome={classification.outcome} reason={classification.reason!r}")
    assert classification.outcome is Outcome.ABORTED


# ======================================================================================
# AC-5 — the rc-independent defence
# ======================================================================================


def test_a_childless_testcase_without_a_name_is_not_a_pass(body_shape: RunRecord) -> None:
    """`parse_junit`'s half. Calling this `"passed"` is what let a contended run read GREEN.

    The two records differ ONLY by the name attribute, which is why the tag has to.
    """
    records = parse_junit(body_shape.xml_text or "")
    nameless = [r for r in records if r.name == UNNAMED_CASE]
    print(f"records={[(r.name, r.tag) for r in records]}")
    assert [r.tag for r in nameless] == ["unreported"]


def test_a_childless_named_testcase_is_still_a_pass(body_shape: RunRecord) -> None:
    """Positive control for AC-5, from the same report: a named childless case is a pass."""
    records = parse_junit(_subset(body_shape.xml_text or "", "test_green"))
    print(f"records={[(r.name, r.tag) for r in records]}")
    assert [r.tag for r in records] == ["passed"]


def test_an_unreported_case_classifies_aborted_without_an_exit_code(
    body_shape: RunRecord, declared: tuple[Claim, Path]
) -> None:
    """Layer 2 alone, with NO exit code — the injected-runner path (B14).

    Probe P9's node. With no `returncode` supplied the exit-code layer cannot fire, so this
    outcome is held by the shape layer and nothing else; disabling that layer drops the
    reading to GREEN.
    """
    result = _classify(body_shape, declared, with_rc=False)
    print(f"rc=- outcome={result.outcome} reason={result.reason!r}")
    assert result.outcome is Outcome.ABORTED and result.reason.startswith(ABORT_LEAD_SHAPE)


# ======================================================================================
# AC-6 — the closed incident replays, and the live shape still matches it
# ======================================================================================


def _measured() -> dict[str, dict[str, object]]:
    return json.loads((FIXTURES / "MEASURED.json").read_text(encoding="utf-8"))


def _classify_fixture(stem: str, declared: tuple[Claim, Path]):
    entry = _measured()[stem]
    claim, path = declared
    xml_text = (FIXTURES / str(entry["junit"])).read_text(encoding="utf-8")
    stdout_name = entry["stdout"]
    tail = (
        (FIXTURES / str(stdout_name)).read_text(encoding="utf-8") if stdout_name is not None else ""
    )
    return classify(
        parse_junit(xml_text),
        claim,
        path,
        path.parent,
        returncode=int(str(entry["returncode"])),
        stdout_tail=tail,
    )


def test_the_s277_body_fixture_classifies_aborted(declared: tuple[Claim, Path]) -> None:
    """The closed incident, replayed. Pre-PLAN-0121 this exact file read GREEN."""
    result = _classify_fixture("s277_exit75_body", declared)
    print(f"rc=75 outcome={result.outcome} (pre_fix_outcome=GREEN)")
    assert result.outcome is Outcome.ABORTED


def test_the_s277_fixture_phase_fixture_classifies_aborted(
    declared: tuple[Claim, Path],
) -> None:
    """The other phase of the same incident. Pre-PLAN-0121 this read NO-TESTS."""
    result = _classify_fixture("s277_exit75_fixture", declared)
    print(f"rc=75 outcome={result.outcome} (pre_fix_outcome=NO-TESTS)")
    assert result.outcome is Outcome.ABORTED


def test_the_s277_green_control_fixture_is_green(declared: tuple[Claim, Path]) -> None:
    """The control captured alongside them: a real green must still read GREEN."""
    result = _classify_fixture("s277_green_control", declared)
    print(f"rc=0 outcome={result.outcome}")
    assert result.outcome is Outcome.GREEN


def test_the_live_body_shape_matches_the_s277_signature(body_shape: RunRecord) -> None:
    """🔴 The drift detector — a claim about **pytest**, not about `tools/`.

    If a future pytest starts naming aborted testcases, layer 2 (§4.3(2)) goes dead while
    layer 1 still holds, and nothing else in this suite would say so. Exempted from the
    probe battery with that written reason: no mutation of `tools/` can reach it.
    """
    live_root = ET.fromstring(body_shape.xml_text or "")  # noqa: S314
    pinned_root = ET.fromstring(  # noqa: S314
        (FIXTURES / "s277_exit75_body.junit.xml").read_text(encoding="utf-8")
    )

    def signature(root: ET.Element) -> tuple[int, int]:
        cases = list(root.iter("testcase"))
        return len(cases), sum(1 for c in cases if c.get("name") is None)

    live_sig, pinned_sig = signature(live_root), signature(pinned_root)
    print(f"live=(cases,nameless){live_sig} pinned=(cases,nameless){pinned_sig}")
    # The live report also carries the green, so only the NAMELESS count is comparable.
    assert live_sig[1] == pinned_sig[1] == 1
