"""Aquaculture vertical — synthetic DataAdapter (PLAN-0016 new-vertical scaffold).

Generated by ``vero-lite new-vertical``. Structurally identical to the
energy/supply_chain adapters; only the object sources differ (proof that a
new vertical is "swap the ontology + adapter"). Serves the synthetic dataset
in ``synthetic.py`` as raw object dicts and streams OperationalEvent dicts —
including one breach the recommender escalates.

``register_aquaculture_adapter`` registers an instance on the process-wide registry
(OQ-6: explicit registration).
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any

from services.engine import demo_events
from services.engine.registry import registry
from verticals.aquaculture.data_adapter import synthetic

_VERTICAL = "aquaculture"


def _operational_events() -> list[dict[str, Any]]:
    """The per-process live OperationalEvent view (PLAN-0015 D1/D2).

    Routes synthetic events through ``demo_events`` so real-time anchoring and
    the execute-time recovery reading apply; with the anchor flag off and no
    execution it equals ``synthetic.operational_events()`` (deterministic).
    """
    return demo_events.events(_VERTICAL, synthetic.operational_events)


_OBJECT_SOURCES = {
    **synthetic.OBJECT_SOURCES,
    "OperationalEvent": _operational_events,
}


class AquacultureSyntheticAdapter:
    """Deterministic synthetic DataAdapter for the aquaculture vertical.

    Conforms structurally to ``services.engine.data_adapter.DataAdapter``.
    No external I/O — every call returns the synthetic dataset, so demos
    and tests are reproducible.
    """

    vertical_name = "aquaculture"

    async def fetch_objects(
        self,
        object_type: str,
        filter_expr: str | None = None,
        limit: int = 1000,
    ) -> list[dict[str, Any]]:
        """Return synthetic object dicts for ``object_type`` (unknown -> empty)."""
        source = _OBJECT_SOURCES.get(object_type)
        if source is None:
            return []
        return source()[:limit]

    async def fetch_links(
        self,
        link_type: str,
        from_pk: str | None = None,
        to_pk: str | None = None,
    ) -> list[dict[str, Any]]:
        """Return link dicts for ``link_type`` (Phase 2 synthetic: none)."""
        return []

    async def stream_events(
        self,
        event_type: str,
        since: datetime | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """Yield synthetic OperationalEvent dicts of ``event_type``."""
        for event in _operational_events():
            if event["event_type"] != event_type:
                continue
            if since is not None and event["occurred_at"] < since:
                continue
            yield event

    async def health_check(self) -> dict[str, Any]:
        """Report adapter status and the synthetic record counts."""
        return {
            "status": "ok",
            "vertical": self.vertical_name,
            "synthetic": True,
            "object_counts": {name: len(src()) for name, src in _OBJECT_SOURCES.items()},
        }


def register_aquaculture_adapter() -> AquacultureSyntheticAdapter:
    """Register a fresh AquacultureSyntheticAdapter on the process-wide registry."""
    adapter = AquacultureSyntheticAdapter()
    registry.register_adapter(adapter)
    return adapter
