"""A monotonic ``seq`` for the task-chain flip trail — the sixth latest-wins site.

Revision ID: 0025
Revises: 0024
Create Date: 2026-08-04

**Why.** ``verticals/fleet_maintenance/task_chain.py::chain_state`` reduces the
append-only flip rows to "what is this checklist item's status now" by sorting on
``at`` — a Python ``datetime.now(UTC)`` stamp written at
``services/api/routers/cases.py``. PLAN-0099 measured that clock on this box over
528M samples across 300 s: it steps BACKWARDS 20 times, every step >= 400 ms,
worst -592 ms. Under a backward step between two flips of the SAME item, the
SUPERSEDED flip sorts last and becomes the reported state.

The ``event_id`` tiebreak never protected this. ``at`` is the leading sort key, so
on an inversion the tiebreak is not consulted at all; and ``event_id`` is
``f"task-{uuid4().hex[:12]}"``, so even on an exact tie it is a coin flip rather
than an order.

**Why it is a correctness path, not a display list.** ``chain_state`` feeds
``stale_items`` feeds ``services/db/task_chain_sweep.py`` — the producer for the
``TASK_CHAIN_STALE`` LINE nudge. Both directions of the inversion are live
failures, and they fail asymmetrically:

* a ``done`` item reduced to ``pending`` is nudged about forever — the partner's
  own stated pilot-killer ("เดี๋ยวคนปิดแจ้งเตือนหมด"), reached by arithmetic
  rather than by a wrong rule;
* a reopened item reduced to ``done`` stops being chased — SILENT, with nothing
  on any screen to notice, discovered only by a truck sitting in a yard.

Both are forced deterministically in ``tests/api/test_task_chain_scenario.py``.

**Why this table was not in the ``0023`` wave.** It was not weighed and excluded —
it was invisible. PLAN-0099's guard scans ``services/`` only, matches only
``order_by`` calls, and only against a nine-name ``_WALL_CLOCK`` vocabulary. This
pick lives in ``verticals/``, sorts in Python rather than in SQL, and its column is
named ``at``. PLAN-0099's Out of Scope records that blind spot in as many words;
this revision is the first instance found inside it.

**Additive-only.** The table is append-only and may hold live dev/demo rows.
Nothing existing is rewritten except the new column's own values, and ``downgrade``
drops only what ``upgrade`` added.

Mechanism, identity mode and the ``setval`` step are ``0023``'s, deliberately
unchanged — see that revision for why ``BY DEFAULT`` rather than ``ALWAYS`` (the
backfill has to write explicit values) and why the UNIQUE constraint is what makes
the looser identity safe. The constraint is ``(tenant_id, seq)`` per PLAN-0101
SD-3, matching the five columns ``0024`` re-scoped; as that revision's siblings
note, the counter is per-TABLE and the pair promises no gap-free per-tenant
monotonicity.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "repair_case_task_event"

#: The backfill order is the CURRENT reader's key — ``chain_state``'s
#: ``sorted(key=(at, event_id))``. Existing rows therefore keep the exact answer
#: they already give, so this revision is a defect fix for FUTURE inversions and
#: not a silent re-interpretation of history. A total order over ``(at, event_id)``
#: refines every per-case order, so each case's relative sequence is preserved.
_ORDER_COL = "at"
_PK = "event_id"


def upgrade() -> None:
    op.add_column(_TABLE, sa.Column("seq", sa.BigInteger(), nullable=True))
    op.execute(
        f"""
        UPDATE {_TABLE} AS t
        SET seq = ordered.rn
        FROM (
            SELECT {_PK} AS pk,
                   row_number() OVER (ORDER BY {_ORDER_COL}, {_PK}) AS rn
            FROM {_TABLE}
        ) AS ordered
        WHERE t.{_PK} = ordered.pk
        """  # noqa: S608
    )
    op.alter_column(_TABLE, "seq", nullable=False)
    op.execute(f"ALTER TABLE {_TABLE} ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY")
    # The identity sequence starts at 1, which would collide with every row the
    # backfill just numbered. ``is_called => false`` makes the next value exactly
    # ``MAX(seq) + 1`` rather than one beyond it, so the series stays gap-free from
    # the first insert.
    op.execute(
        f"""
        SELECT setval(
            pg_get_serial_sequence('{_TABLE}', 'seq'),
            COALESCE((SELECT MAX(seq) FROM {_TABLE}), 0) + 1,
            false
        )
        """  # noqa: S608
    )
    op.create_unique_constraint(f"uq_{_TABLE}_seq", _TABLE, ["tenant_id", "seq"])


def downgrade() -> None:
    op.drop_constraint(f"uq_{_TABLE}_seq", _TABLE, type_="unique")
    # Dropping the column takes its identity sequence with it — Postgres owns that
    # sequence and drops it with the column, so nothing is left for a re-``upgrade``
    # to trip on.
    op.drop_column(_TABLE, "seq")
