"""Synthetic dataset for the procurement vertical (PLAN-0016 scaffold).

Generated by ``vero-lite new-vertical`` — a minimal, deterministic starting
point (no external I/O, reproducible). Shapes match the vertical ontology.

⚠ DRAFT FOR HUMAN REVIEW (ADR-0015 D5): review + enrich these records (domain-
plausible names, a fuller timeline) before the demo. The breach event is the
timeline's final beat so real-time anchoring (PLAN-0015 D1) leaves nothing in the
future.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


def plant_records() -> list[dict[str, Any]]:
    """Return the synthetic Plant records (geo-bearing)."""
    return [
        {
            "plant_id": "plant-01",
            "name": "Plant 01",
            "plant_type": "assembly",
            "lat": 13.75,
            "lng": 100.5,
        },
    ]


def equipment_records() -> list[dict[str, Any]]:
    """Return the synthetic Equipment records."""
    return [
        {
            "equipment_id": "equipment-01",
            "name": "Equipment 01",
            "equipment_type": "cnc_machine",
            "criticality": "low",
            "status": "operational",
            "site_id": "plant-01",
        },
    ]


def operational_events() -> list[dict[str, Any]]:
    """Return the synthetic OperationalEvent records (baseline + breach)."""
    return [
        {
            "event_id": "event-reading-01",
            "event_type": "reading",
            "severity": "info",
            "measured_value": 0.4,
            "unit": "",
            "description": "Equipment 01 equipment criticality nominal.",
            "occurred_at": datetime(2026, 6, 1, 1, 30, tzinfo=UTC),
            "equipment_id": "equipment-01",
            "site_id": "plant-01",
        },
        {
            "event_id": "event-reading-02",
            "event_type": "reading",
            "severity": "critical",
            "measured_value": 0.88,
            "unit": "",
            "description": "Equipment 01 equipment criticality rose above the 0.8  threshold.",
            "occurred_at": datetime(2026, 6, 1, 2, 0, tzinfo=UTC),
            "equipment_id": "equipment-01",
            "site_id": "plant-01",
        },
    ]


OBJECT_SOURCES = {
    "Plant": plant_records,
    "Equipment": equipment_records,
}
