#!/usr/bin/env python3
"""Guard: every ORM module must be imported by BOTH metadata registration sites.

``Base.metadata`` is populated purely by import side effect, so it describes only
the ORM modules the importing process happened to pull in. Two files exist solely
to make that set complete, and both must list every model module:

* ``alembic/env.py`` — what migrations compare against.
* ``tests/db_support.py`` — what a test process' ``create_all`` builds from.

**The failures this exists to prevent, both of which already shipped.** PR #965
added a table with its migration, its ORM and two green suites — and env.py never
imported the module, so CI's ``alembic check`` reported that autogenerate wanted
to **DROP** it. The #965 fix then patched env.py *only*, leaving db_support.py
drifted for a whole PR (found by probe, 2026-07-29). Earlier, the same class hit
``action_identity``: absent from the test-side list, ``create_all`` skipped it and
``drop_all`` left it standing for the next ``alembic upgrade head`` to trip over
with a DuplicateTableError.

That history is why this is a guard rather than a comment: the convention
"keep these in lockstep" was written down in db_support.py and still drifted
twice.

**Only this guard can see the test-side half.** ``alembic check`` compares the
database against the metadata *env.py* builds — it does not know db_support.py
exists, and no number of runs would ever reveal a gap there.

**Why the test suite cannot catch it.** DB-backed tests build their schema with
``Base.metadata.create_all``, and ``Base.metadata`` only knows the models that the
*importing test module* pulled in. Both new suites imported the model class
directly, so the table existed for them. Nothing offline ever traverses
``env.py``, which is the only path production migrations take. 3528 passing tests
did not touch it.

**Why not just run ``alembic check`` locally.** It needs a live database at
``DATABASE_URL``. A pre-commit hook that fails whenever Postgres is down (or in a
worktree, which has no ``.env``) is a hook developers learn to bypass, and a
bypassed guard protects nothing. So the two are split by what they can prove
offline: this guard is static, deterministic and needs no database — it catches
the *unregistered module* class; CI's ``alembic check`` keeps catching
column-level drift, which genuinely requires a database to see.

**Why AST rather than grep.** ``services/engine/code_generator.py`` contains the
text ``__tablename__`` inside the source template it emits. A grep counts it as a
model module and demands env.py import a code generator. Parsing finds
``__tablename__`` only where it is really a class attribute.

Exit codes: 0 = every ORM module is registered; 1 = at least one is not.

``ALEMBIC_GUARD_ROOT`` overrides the repo root for tests (mirrors the
``STATUS_SIZE_PATH`` override-family pattern).
"""

from __future__ import annotations

import ast
import os
import sys
from pathlib import Path

#: Where ORM modules may live. Scoped rather than repo-wide so a fixture or a
#: scratch script that happens to declare a table cannot fail the build.
_MODEL_ROOTS = ("services",)

#: Every file that must import the full model set, and what breaks when it does
#: not. The consequence is carried alongside the path because the two sites fail
#: in completely different ways, and a guard that said only "add an import" would
#: leave the reader guessing which one they are looking at.
_REGISTRATION_SITES: tuple[tuple[Path, str], ...] = (
    (
        Path("alembic") / "env.py",
        "migrations compare against this metadata — a missing module means "
        "`alembic check` fails in CI and the next autogenerated migration "
        "proposes DROPPING the table",
    ),
    (
        Path("tests") / "db_support.py",
        "a test process' `create_all` builds from this metadata — a missing "
        "module means the table is silently skipped at create and left standing "
        "at drop, for the next `alembic upgrade head` to hit with a "
        "DuplicateTableError",
    ),
)


def _defines_a_table(source: str) -> bool:
    """True if this module declares a real ``__tablename__`` CLASS attribute.

    Text inside a string template does not count — see the module docstring.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        # A file that does not parse is not this guard's problem; ruff and mypy
        # both fail first and say so far better than a table check could.
        return False

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for statement in node.body:
            targets: list[ast.expr] = []
            if isinstance(statement, ast.Assign):
                targets = list(statement.targets)
            elif isinstance(statement, ast.AnnAssign):
                targets = [statement.target]
            for target in targets:
                if isinstance(target, ast.Name) and target.id == "__tablename__":
                    return True
    return False


def find_model_modules(root: Path) -> set[str]:
    """Every dotted module path under the model roots that declares a table."""
    found: set[str] = set()
    for model_root in _MODEL_ROOTS:
        for path in (root / model_root).rglob("*.py"):
            if "__pycache__" in path.parts:
                continue
            if _defines_a_table(path.read_text(encoding="utf-8")):
                found.add(path.relative_to(root).with_suffix("").as_posix().replace("/", "."))
    return found


def find_registered_modules(env_source: str) -> set[str]:
    """Every dotted module path ``alembic/env.py`` imports.

    Both spellings are resolved, because env.py uses both:
    ``from services.db import repair_case`` -> ``services.db.repair_case``, and
    ``import services.db.repair_case`` -> the same. The ``from X import Y`` form
    is ambiguous in the abstract (``Y`` could be a name, not a module), which is
    harmless here: a name that is not a module simply never matches a discovered
    model module.
    """
    registered: set[str] = set()
    tree = ast.parse(env_source)
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                registered.add(f"{node.module}.{alias.name}")
        elif isinstance(node, ast.Import):
            for alias in node.names:
                registered.add(alias.name)
    return registered


def main() -> int:
    root = Path(os.environ.get("ALEMBIC_GUARD_ROOT") or ".").resolve()
    models = find_model_modules(root)
    failed = False

    for relative, consequence in _REGISTRATION_SITES:
        path = root / relative
        if not path.exists():
            # A checkout without one of the sites (or the fixture trees the guard's
            # own tests build) is not a violation — there is simply nothing to
            # register against.
            continue

        missing = sorted(models - find_registered_modules(path.read_text(encoding="utf-8")))
        if not missing:
            continue

        failed = True
        print(
            "alembic-model-registration: these ORM modules declare a table but are "
            f"NOT imported by {relative.as_posix()}:\n"
            + "".join(f"  - {name}\n" for name in missing)
            + f"\nWhy it matters here: {consequence}.\n"
            f"Add to {relative.as_posix()}:\n"
            + "".join(
                f"  from {name.rsplit('.', 1)[0]} import {name.rsplit('.', 1)[1]}"
                f"  # noqa: F401\n"
                for name in missing
            ),
            file=sys.stderr,
        )

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
